Add Home Assistant OS installation
airalab/robonomics-wiki pull request #386
Opened 2022-11-29 19:34 UTC by LoSk-p

2022-11-29 19:59 UTC, PaTara43 requested changes
Пара правок. Сейчас не могу посмотреть и проверить в самом хассе. А так - круть

2022-11-29 19:59 UTC, PaTara43 commented on docs/upgrade-hass-os.md
> +**This article contains instructions to upgrade your existing Home Assistant OS with Robonomics Integration.**
```suggestion
**This article contains instructions to upgrade your existing Home Assistant OS with Robonomics integration.**
```

2022-11-29 19:59 UTC, PaTara43 commented on docs/upgrade-hass-os.md
> +Robonomics Integration stores the data using local IPFS daemon, so you need to install it first. There is an [IPFS Add-on for Home Assistant](https://github.com/LoSk-p/ipfs-addon).
Не хочешь это в wiki-note?

2022-11-29 19:59 UTC, PaTara43 commented on docs/upgrade-hass-os.md
> +Now that the integration is added to the folder of custom components of Home Assistant, you have two options:
Ориентируйся на переписанное Иваном
https://wiki.robonomics.network/docs/upgrade-your-hass-core#verify

2022-11-29 19:59 UTC, PaTara43 commented on docs/upgrade-hass-os.md
> +Now that the integration is added to the folder of custom components of Home Assistant, you have two options:
Там в конце

2022-11-30 04:47 UTC, PaTara43 approved these changes

2022-11-30 09:42 UTC, Fingerling42 approved these changes

2022-11-30 10:36 UTC, merged