Update backups page
airalab/robonomics-wiki pull request #651
Opened 2023-06-07 13:09 UTC by LoSk-p

2023-06-07 13:38 UTC, tubleronchik commented on docs/backup-services.md
> +1. Install Home Assisntant with Robonomics Integration, following the steps from the article for needed installation method.
..."for the desired installation method" might be better

2023-06-07 13:41 UTC, PaTara43 requested changes

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +In order to restore your configuration, it is necessary to use a **custom IPFS gateway** such as Pinata. Without it, your backup will be stored solely on your local IPFS node, which may prevent you f
мб не только restore, но и сам бэкап?

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +In order to restore your configuration, you will need installed Home Assistant and Robonomics Integration.
you need to install чем не понравилось?)

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +1. Install Home Assisntant with Robonomics Integration, following the steps from the article for needed installation method.
for according installation method. мб ссыль дать на overview?

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +2.  [Set up Robonomics Integration](https://wiki.robonomics.network/docs/robonomics-hass-integration) using **the same seeds** you used in previous Robonomics configuration. If you subscription has b
subscription has ended

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +4. After restoring, Home Assistant will automatically restart. If for some reason Home Assistant does not restart, you can check the restoration status by monitoring the state of the `robonomics.back
If the status is `restored`

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +- **Path to Zigbee2MQTT config**  (default: `/opt/zigbee2mqtt`) - If you used Home Assistant Core or Docker installation methods and have not default path to Zigbee2MQTT, you should change this param
напомни, почему этого не указываем при создании бэкапа?

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +## Restore Mosquitto and Zigbee2MQTT Configuration for Home Assistant Core Installation Method
Надо как-то переименовать тогда предыдущий заголовок, чтобы не было путанницы, а то я пойду по порядку, там рестор, а только внизу core и докер

или отдельно указать, что для них - ниже

2023-06-07 13:41 UTC, PaTara43 commented on docs/backup-services.md
> +```bash
для compose есть вариант?

2023-06-07 13:55 UTC, PaTara43 commented on docs/backup-services.md
> +In order to restore your configuration, you will need installed Home Assistant and Robonomics Integration.
тогда an installed

2023-06-07 13:58 UTC, LoSk-p commented on docs/backup-services.md
> +- **Path to Zigbee2MQTT config**  (default: `/opt/zigbee2mqtt`) - If you used Home Assistant Core or Docker installation methods and have not default path to Zigbee2MQTT, you should change this param
Для москито указывает, а z2m делается через вызоа из сервиса через mqtt, так что там путь не нужен (а вот сервиса для восстановления у них нет)

2023-06-07 14:13 UTC, PaTara43 commented on docs/backup-services.md
> +- **Path to Zigbee2MQTT config**  (default: `/opt/zigbee2mqtt`) - If you used Home Assistant Core or Docker installation methods and have not default path to Zigbee2MQTT, you should change this param
точно

2023-06-08 11:38 UTC, PaTara43 approved these changes

2023-06-08 11:39 UTC, merged