create article PTZ camera
airalab/robonomics-wiki pull request #688
Opened 2023-06-28 15:58 UTC by nakata5321

Create article - how to control PTZ camera from Home assistant

2023-06-29 08:20 UTC, Vourhey commented on docs/ptz-camera.md
> +To use it usually you have to set up local camera account, his process won't be covered in this article.
this process

2023-06-29 08:20 UTC, Vourhey commented on docs/ptz-camera.md
> +To use it usually you have to set up local camera account, his process won't be covered in this article.
and maybe highlight the warning that the process of setting up the local camera account is not going to be covered in the article

2023-06-29 08:20 UTC, Vourhey commented on docs/ptz-camera.md
> +You already fully setup camera to Home Assistant. Now let's provide camera stream and control buttons to dashboard.
English. Please put Russian text to google translate and copy paste the result

2023-07-03 10:25 UTC, PaTara43 requested changes

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +Additionally, you can add the stream to your dashboard. To do this, let's go to it and create a new card
```suggestion
Additionally, you can add the stream to your dashboard. To do this, navigate to the dashboard and create a new card 
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +To send a video to Robonomics, you should call a service "Robonomics: Save recording to robonomics ". Now you will do it manually, but later you can create automation for it.
А вообще, у тебя тут повтор названия сервиса, можно избежать

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +Fill in the fields and call the service with the "CALL SERVICE" button.
```suggestion
Fill in the data and call the service with the "CALL SERVICE" button.
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +to view the received video go to [Robonomics DAPP](https://vol4tim.github.io/videostream/).
```suggestion
To view the resulted video go to [Robonomics DAPP](https://vol4tim.github.io/videostream/).
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +Paste in your controller's account address and click the button. Wait while the search for twins is in progress.
```suggestion
Paste in your controller's account address and click the button below. Wait for the "Search for Twins" process. 
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +As a result, you will get an IPFS hash with all recorded videos.
```suggestion
As a result, you will get an IPFS CID with all recorded videos.
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +the web3 ipfs gateway to download all the videos. As a result, we see all the videos recorded by our smart home.
```suggestion
the Web3 IPFS gateway to download all the videos. As a result, you will obtain see all the videos recorded by your smart home.
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +Since all the videos in the folder are encrypted with the controller key, you need to insert them to decrypt videos.
```suggestion
Since all the videos in the folder are encrypted with the controller key, you need to insert it to decrypt videos.
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +After that, the video playback button is activated. After clicking on the play button,
```suggestion
After that, the video playback button is activated. Click on it to download the video.
```

2023-07-03 10:25 UTC, PaTara43 commented on docs/robonomics-video.md
> +the video is downloaded, and it will become available for playback.
```suggestion

```

2023-07-03 11:36 UTC, nakata5321 commented on docs/robonomics-video.md
> +If you have RTZ camera, check ["RTZ camera" article](/docs/ptz-camera). And then go to second step here.
А вот не ведь должен не просто вернуться к это статье, но и пропустить первый шаг тут (который  "Connect the Camera")

2023-07-03 11:54 UTC, nakata5321 commented on docs/robonomics-video.md
> +In Preview window activate the checkbox "This image looks good." and then the "Submit" button. And finish installation.
Не так. После нажатия кнопки Submit бкдет еще одно окошко, где скажут что установка завершена и надо будет нажать кнопку "Finish". Поэтому последняя правка не верна

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +the video is downloaded, and it will become available for playback.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +After that, the video playback button is activated. After clicking on the play button,
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +the web3 ipfs gateway to download all the videos. As a result, we see all the videos recorded by our smart home.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +As a result, you will get an IPFS hash with all recorded videos.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +Paste in your controller's account address and click the button. Wait while the search for twins is in progress.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +to view the received video go to [Robonomics DAPP](https://vol4tim.github.io/videostream/).
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +Fill in the fields and call the service with the "CALL SERVICE" button.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:17 UTC, nakata5321 commented on docs/robonomics-video.md
> +- For Home Assistant Core - Path to the folder, where you create a media folder.
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:18 UTC, nakata5321 commented on docs/robonomics-video.md
> +in "Path to save the recording" you should provide an absolute path to the folder,
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-03 14:18 UTC, nakata5321 commented on docs/robonomics-video.md
> +To do this, go to "Developer tools" -> "Services" and find "Robonomics: Save recording to robonomics ".
https://github.com/airalab/robonomics-wiki/pull/688/commits/628c50bc9368a4d6fbb259e735b3b16f6ae99346

2023-07-04 09:54 UTC, PaTara43 requested changes

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Or you have to fill in all fields manually. You will see the next window.
```suggestion
Otherwise you have to fill in all the fields manually. You will see the following window.
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Fill in the fields:
```suggestion
Fill in the gaps:
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Fill in the fields:
просто убрать повторения

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +- Username - write a username of your camera **device** account
```suggestion
- Username - write a username of your camera local account
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +- Password - write a password for your camera **device** account
```suggestion
- Password - write a password for your camera local account
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +and press "Submit". Choose an Area for your camera and "Finish" installation.
```suggestion
and press "Submit". Choose an Area for your camera and click on "Finish".
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +You already fully set up the camera to Home Assistant.
```suggestion
Now that you have fully set up the camera, you may add its stream and control buttons to the dashboard.
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Now let's provide a camera stream and control buttons to the dashboard.
```suggestion

```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Go to the dashboard and start creating a new card. Choose the "Picture Glance" card.
```suggestion
Go to the dashboard and start with creating a new card. Choose the "Picture Glance" one.
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Change nest fields:
```suggestion
Fill in the data:
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +- Name - Write a place where you install the camera
```suggestion
- Title - choose camera image title
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +- Camera Entity - Choose a camera entity from the drop list
```suggestion
- Camera Entity - choose a camera entity from the drop-down list
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +- Camera View - choose "live" to get less time lag
```suggestion
- Camera View - choose "live" to get less delay```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Next, change to "Code Editor" mode by pressing the button at the bottom left side. You will see the next code:
```suggestion
Next, switch to "Code Editor" mode by pressing the button at the bottom left side. You will see the following code:
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Instead of `entities: []` line insert next (The list of entities could be not empty. Then delete all lines with entities):
```suggestion
Replace the content of `entities: []` according to the example below (`<YOUR_CAMERA_ENTITY>` is the same as the `camera_image` parameter):
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +Then copy the camera entity id from the "camera_image" key. (In the example it's `camera.tapo_mainstream`.)
```suggestion
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +And insert it in place of `<YOUR_CAMERA_ENTITY>`. Save configuration.
```suggestion
```

2023-07-04 09:54 UTC, PaTara43 commented on docs/ptz-camera.md
> +That's all. Now you should see Card on the dashboard with control buttons.
```suggestion
That's all. Now you should see the RTZ camera card on the dashboard along with control buttons.
```

2023-07-04 11:05 UTC, PaTara43 approved these changes

2023-07-04 11:05 UTC, merged